### ISSUE TITLE
Do something with `send`'s spoof option

### ISSUE THREAD

**Issue by VoxSecundus** [openflighthpc/flight-hunter#21]
Currently, I don't think that the `--spoof` option on `send` does anything. We would like to remove it and replace it with a new option/set of options that allow a client to send a prefix/label/group along with its data/payload. What the server does with the data is out of the scope of this feature specification, as long as it is being stored in the node list. How the data is stored is up to the developer, but my mind tells me that anything the node stores as "pre-fabricated metadata" ought to be stored in its own array YAML attribute.

**Comment by ColonelPanicks** [comment]
Just here to note that label/prefix are mutually exclusive and that group is separate of both. All would be optional.
