### ISSUE TITLE
`--include-self` not always authorised

### ISSUE THREAD

**Issue by Womblue** [openflighthpc/flight-hunter#39]
When using `--include-self` and `--auth` on a server, i.e.
```
bin/hunter hunt --include-self --auth secretcode
```
Hunter is unable to include itself because the authentication keys do not match. The internal `send` command should include the authentication key given in `hunt`.

**Comment by VoxSecundus** [comment]
This could have one of two solutions:

1. We add the value of `auth_key` at runtime to the arguments passed to send [here](https://github.com/openflighthpc/flight-hunter/blob/master/lib/hunter/commands/hunt.rb#L68)
2. We find a better way to invoke the `send` logic without invoking the top-level command. This would be a bit more involved, and would probably require extracting a lot of the `send` logic from the command class into somewhere more easily accessible.

**Comment by Womblue** [comment]
For now I've passed the auth key argument to fix the issue, but I'm a fan of having `--include-self` insert its own data into the buffer rather than invoking `send`.

**Comment by VoxSecundus** [comment]
> but I'm a fan of having --include-self insert its own data into the buffer rather than invoking send in future.

Maybe it's how I interpret it, but that sounds like it would be bypassing the usual logic for receiving/saving a node; it would be better to use the same logic for both situations.

**Comment by Womblue** [comment]
For the time being there's no need to change it, and I do see your point that using the same logic for both would keep the process consistent.

**Comment by VoxSecundus** [comment]
Resolved in #41
